### ISSUE TITLE
theme should provide own set of default widgets

### ISSUE THREAD

**Issue by btd** [MatejMazur/react-schema-form#6]
Currently there is only one place where default widget selected.
What was good in original rjsf is that it has nice set of ui defaults defined. So what i mean exactly:
```js
{
  type: 'object',
  properties: {
    a: {
      type: 'integer'
    }
  }
}
```

And this field `a` would be rendered as `input type=text` instead of updown widget. Currenlty this is only possible with additional uiSchema defined

**Comment by MatejMazur** [comment]
Hi, `type: 'integer'` is rendered with updown widget in rjsf. This lib uses the same widgetMap as rjsf so there shouldn't be any differences.

**Comment by btd** [comment]
I think you are right. I just noticed i always set updown in uiSchema.
